// <auto-generated />
using System;
using AgendaInfo.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaInfo.Migrations
{
    [DbContext(typeof(BDDContext))]
    partial class BDDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Agenda.Models.POCO.Evaluation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(244)")
                        .HasMaxLength(244);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<int?>("RendezVousID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("RendezVousID");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("Agenda.Models.POCO.RendezVous", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("ServiceID");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("AdminID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Agenda.Models.POCO.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Type").HasValue("User");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Admin", b =>
                {
                    b.HasBaseType("Agenda.Models.POCO.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Customer", b =>
                {
                    b.HasBaseType("Agenda.Models.POCO.User");

                    b.Property<int?>("AdminID")
                        .HasColumnType("int");

                    b.HasIndex("AdminID");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Evaluation", b =>
                {
                    b.HasOne("Agenda.Models.POCO.Customer", null)
                        .WithMany("ListEvaluation")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Agenda.Models.POCO.RendezVous", "RendezVous")
                        .WithMany()
                        .HasForeignKey("RendezVousID");
                });

            modelBuilder.Entity("Agenda.Models.POCO.RendezVous", b =>
                {
                    b.HasOne("Agenda.Models.POCO.Customer", "Customer")
                        .WithMany("ListRendezVous")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Agenda.Models.POCO.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Service", b =>
                {
                    b.HasOne("Agenda.Models.POCO.Admin", null)
                        .WithMany("ListServices")
                        .HasForeignKey("AdminID");
                });

            modelBuilder.Entity("Agenda.Models.POCO.Customer", b =>
                {
                    b.HasOne("Agenda.Models.POCO.Admin", null)
                        .WithMany("ListCustomers")
                        .HasForeignKey("AdminID");
                });
#pragma warning restore 612, 618
        }
    }
}
